### ISSUE TITLE
Detailed Placement checks failed

### ISSUE THREAD

**Issue by lulu9312** [The-OpenROAD-Project/OpenROAD-flow-scripts#556] opened 2022-08-13 08:12 UTC
Describe the bug
I have done manual macro placement and also created a voltage domain.Getting error at detailed placement stage

Expected behavior
Should pass the detailed placement stage

Screenshots
![error_1](https://user-images.githubusercontent.com/61928883/184475961-298052c2-f7c0-4a96-a821-3f5c2d87b6ef.png)
![error_2](https://user-images.githubusercontent.com/61928883/184475964-1823c9af-417d-4f08-85fd-42e1673b329f.png)
![error_3](https://user-images.githubusercontent.com/61928883/184475967-86829f6f-b25c-4013-8c86-c3fd72307c88.png)

**Comment by lulu9312** [comment] 2022-08-13 08:37
Also attaching the files I used in ORFS
[Test_case.zip](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/9331109/Test_case.zip)

**Comment by vijayank88** [comment] 2022-08-13 09:06
@lulu9312 
Run following command and attach the test case generated by flow script.
`make detail_place_issue`

**Comment by lulu9312** [comment] 2022-08-13 10:26
@vijayank88 here's the generated test case. I have updated CELL_PAD_IN_SITES variable but the error looks same
[detail_place_ldo_sky130hvl_base_2022-08-13_15-53.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/9331228/detail_place_ldo_sky130hvl_base_2022-08-13_15-53.tar.gz)

**Comment by maliberty** [comment] 2022-08-13 14:52
The problem is that the placement rows around the voltage domain are malformed.  The fix is initial_floorplan to correctly setup the rows.
![image](https://user-images.githubusercontent.com/761514/184499401-1d6586b6-20dc-4e74-9222-d84b12a38eac.png)

**Closed as completed** 2022-08-13 15:44 UTC
