### ISSUE TITLE
Error running gcd

### ISSUE THREAD

**Issue by ApeachM** [The-OpenROAD-Project/OpenROAD-flow-scripts#1672] opened 2023-12-02 01:12 UTC
### Subject

[Documentation] for documentation errors.

### Describe the bug

I am trying to running ORFS in Window.
I installed WSL2 and Docker.

In the WSL2, 
```shell
git clone --recursive https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts
cd OpenROAD-flow-scripts
./build_openroad.sh 

```
And I could check the install is finished with below command.
```shell
source ./env.sh
yosys -help
openroad -help
```

To build examples, 
```shell

sudo ./setup.sh
cd flow
util/docker_shell make
```
but there was an error for running following belows.
```shell
OpenROAD v2.0-11117-g6061c4892 
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
clock_tree_synthesis -root_buf BUF_X4 -buf_list BUF_X4 -sink_clustering_enable -sink_clustering_size 30 -sink_clustering_max_diameter 100 -balance_levels
[INFO CTS-0049] Characterization buffer is: BUF_X4.
[INFO CTS-0039] Number of created patterns = 12240.
[INFO CTS-0084] Compiling LUT.
Min. len    Max. len    Min. cap    Max. cap    Min. slew   Max. slew
2           8           1           35          1           12          
[WARNING CTS-0043] 1632 wires are pure wire and no slew degradation.
TritonCTS forced slew degradation on these wires.
[INFO CTS-0046]     Number of wire segments: 12240.
[INFO CTS-0047]     Number of keys in characterization LUT: 1660.
[INFO CTS-0048]     Actual min input cap: 1.
[INFO CTS-0007] Net "clk" found for clock "core_clock".
[INFO CTS-0010]  Clock net "clk" has 35 sinks.
[INFO CTS-0008] TritonCTS found 1 clock nets.
[INFO CTS-0097] Characterization used 1 buffer(s) types.
[INFO CTS-0200] 0 placement blockages have been identified.
[INFO CTS-0201] 0 placed hard macros will be treated like blockages.
[INFO CTS-0027] Generating H-Tree topology for net clk.
[INFO CTS-0028]  Total number of sinks: 35.
[INFO CTS-0029]  Sinks will be clustered in groups of up to 30 and with maximum cluster diameter of 100.0 um.
[INFO CTS-0030]  Number of static layers: 0.
[INFO CTS-0020]  Wire segment unit: 14000  dbu (7 um).
[INFO CTS-0023]  Original sink region: [(5880, 4030), (59850, 57570)].
[INFO CTS-0024]  Normalized sink region: [(0.42, 0.287857), (4.275, 4.11214)].
[INFO CTS-0025]     Width:  3.8550.
[INFO CTS-0026]     Height: 3.8243.
[WARNING CTS-0045] Creating fake entries in the LUT.
 Level 1
    Direction: Horizontal
    Sinks per sub-region: 18
    Sub-region size: 1.9275 X 3.8243
[INFO CTS-0034]     Segment length (rounded): 1.
    Key: 12276 inSlew: 1 inCap: 1 outSlew: 2 load: 1 length: 1 delay: 1
 Level 2
    Direction: Vertical
    Sinks per sub-region: 9
    Sub-region size: 1.9275 X 1.9121
[INFO CTS-0034]     Segment length (rounded): 1.
    Key: 12276 inSlew: 1 inCap: 1 outSlew: 2 load: 1 length: 1 delay: 1
[INFO CTS-0032]  Stop criterion found. Max number of sinks is 15.
[INFO CTS-0035]  Number of sinks covered: 35.
[INFO CTS-0018]     Created 5 clock buffers.
[INFO CTS-0012]     Minimum number of buffers in the clock path: 2.
[INFO CTS-0013]     Maximum number of buffers in the clock path: 2.
[INFO CTS-0015]     Created 5 clock nets.
[INFO CTS-0016]     Fanout distribution for the current clock = 7:1, 8:1, 10:2..
[INFO CTS-0017]     Max level of the clock tree: 2.
[INFO CTS-0098] Clock net "clk"
[INFO CTS-0099]  Sinks 35
[INFO CTS-0100]  Leaf buffers 0
[INFO CTS-0101]  Average sink wire length 48.28 um
[INFO CTS-0102]  Path depth 2 - 2

==========================================================================
cts pre-repair report_check_types -max_slew -max_cap -max_fanout -violators
--------------------------------------------------------------------------
0.4655
0.8882

==========================================================================
cts pre-repair report_design_area
--------------------------------------------------------------------------
Design area 550 u^2 61% utilization.
[INFO RSZ-0058] Using max wire length 661um.

==========================================================================
cts post-repair report_check_types -max_slew -max_cap -max_fanout -violators
--------------------------------------------------------------------------
0.4655
0.8882

==========================================================================
cts post-repair report_design_area
--------------------------------------------------------------------------
Design area 550 u^2 61% utilization.
Placement Analysis
---------------------------------
total displacement          9.9 u
average displacement        0.0 u
max displacement            2.5 u
original HPWL            1773.8 u
legalized HPWL           1842.1 u
delta HPWL                    4 %

Repair setup and hold violations...
TNS end percent 100
[INFO RSZ-0094] Found 43 endpoints with setup violations.
[INFO RSZ-0040] Inserted 19 buffers.
[INFO RSZ-0041] Resized 79 instances.
[INFO RSZ-0043] Swapped pins on 31 instances.
[INFO RSZ-0049] Cloned 2 instances.
[WARNING RSZ-0062] Unable to repair all setup violations.
[INFO RSZ-0033] No hold violations found.
Error: cts.tcl, 113 couldn't execute "eqy": no such file or directory
Command exited with non-zero status 1
Elapsed time: 0:04.65[h:]min:sec. CPU time: user 4.55 sys 0.07 (99%). Peak memory: 117148KB.
```

### Expected Behavior

Running correctly 

### Environment

Running the docker container, and I did 

```shell
docker run --rm -it -u $(id -u ${USER}):$(id -g ${USER}) -v $(pwd)/flow:/OpenROAD-flow-scripts/flow openroad/flow-centos7-builder
```

```
cd tools/OpenROAD
./etc/Env.sh
```
But the message is abnormal. Is the reason that I used the docker? When I run ./openroad in tools/install/OpenROAD, it works well..

```
bash-4.2$ ./etc/Env.sh
tee: build/openroad-env.log: Permission denied
Unknown git commit, this is not a git repository.

Please make sure that you have the latest code changes and add the commit
hash in the description.

kernel: Linux 5.15.133.1-microsoft-standard-WSL2
os: CentOS Linux 7 (Core)
cmake version 3.24.2
CMake Warning at CMakeLists.txt:98 (message):
  OpenROAD git describe failed, using sha1 instead


CMake Error at CMakeLists.txt:112 (message):
  Insufficient gcc version.  Found 4.8.5, but require >= 8.3.0.


-- The CXX compiler identification is GNU 4.8.5
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- OpenROAD version: HEAD-HASH-NOTFOUND
-- Configuring incomplete, errors occurred!
```

### To Reproduce

Mentioned above.

**Comment by chinayly** [comment] 2023-12-07 03:46
I have the same question in Ubuntu22.04, I still cannot solve it

**Comment by chinayly** [comment] 2023-12-07 03:46
I have the same question in Ubuntu22.04, I still cannot solve it

**Comment by chinayly** [comment] 2023-12-07 03:46
I have the same question in running the OpenROAD-flow-script on Ubuntu22.04, I still cannot solve it

**Comment by chinayly** [comment] 2023-12-07 03:47
I have the same question in running the OpenROAD-flow-script on Ubuntu22.04, I still cannot solve it

**Comment by maliberty** [comment] 2023-12-07 05:17
@vvbandeira please answer re: eqy

**Comment by vijayank88** [comment] 2023-12-07 05:38
Duplicate of https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/1513 
@chinayly  @ApeachM 
Check this comment: https://github.com/The-OpenROAD-Project/OpenROAD/issues/4035#issuecomment-1736369365
You may use prebuilt one as per this comment: https://github.com/The-OpenROAD-Project/OpenROAD/issues/4035#issuecomment-1734753815

**Comment by vvbandeira** [comment] 2024-01-16 11:24
@chinayly @ApeachM 
Could you try again with the latest code? Please also make sure to `source env.sh` before running the flow if you used `sudo ./setup.sh` to install the dependencies.

**Comment by maliberty** [comment] 2024-03-05 23:43
Stale - reopen if still relevant

**Closed as completed by maliberty** 2024-03-05 23:43 UTC
